In [2]:
from keras.models import load_model
model = load_model('FFNN_Deep_1.keras')

In [3]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                      │ (None, 16)                  │              80 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 40)                  │             680 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 10)                  │             410 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 3)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,611 (14.11 KB)

 Trainable params: 1,203 (4.70 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,408 (9.41 KB)

In [6]:
test_data = [[1.2,2.4,4.2,5.3]]

In [20]:
import numpy as np

test_data = np.array([
    [1.2, 2.4, 4.2, 5.3],
    [1.1, 2.2, 3.0, 4.0],
    [4.6 , 3.6 , 1. , 0.2]
])
result = model.predict(test_data)
print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[5.2321476e-14 1.4828882e-07 9.9999988e-01]
 [7.8976925e-10 2.4990597e-05 9.9997497e-01]
 [9.9999344e-01 6.3755615e-06 2.8422906e-07]]


In [21]:
label = np.argmax(result,axis=1)
print(label)

[2 2 0]


In [22]:
prob = np.max(result,axis=1)
print(prob)

[0.9999999  0.99997497 0.99999344]
